print("What is your name,human")
leex = input()    
print("how old are you(in years)?")
age = int(input())
print("How Tall are you(in m)?")
heigh =float(input())
print("how much do you weigh(in kg)?")
weight = float(input())
bmi - weight/(height*height)
print(f"{Alex} you are {34}) years old. Your BMI is{23"})